# Generated by Django 4.2.7 on 2024-06-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vtu_number', models.CharField(max_length=10)),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('banner_image', models.URLField()),
                ('event_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('general_rules', models.TextField()),
                ('dates_and_deadlines', models.TextField()),
                ('prizes', models.TextField()),
                ('registered_teams_count', models.IntegerField(default=0)),
                ('team_size_info', models.CharField(max_length=100)),
                ('registration_deadline', models.DateField()),
                ('coordinators', models.ManyToManyField(to='events.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('member1_name', models.CharField(max_length=100)),
                ('member1_vtu_number', models.CharField(max_length=10)),
                ('member1_year', models.IntegerField()),
                ('member2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member2_vtu_number', models.CharField(blank=True, max_length=10, null=True)),
                ('member2_year', models.IntegerField(blank=True, null=True)),
                ('member3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member3_vtu_number', models.CharField(blank=True, max_length=10, null=True)),
                ('member3_year', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
