# Generated by Django 4.2.7 on 2024-08-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
