# Generated by Django 4.2.7 on 2024-08-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='domain',
        ),
        migrations.AddField(
            model_name='registration',
            name='member1_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
