# Generated by Django 4.2.7 on 2024-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_team_size_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='general_rules',
            field=models.TextField(default='• Participants must adhere to the theme announced at the beginning of the event.\n• All assets used in the game (art, music, etc.) must either be original or properly attributed.\n• Teams can have a maximum of 3 members.\n• Games must be submitted before the deadline to be eligible for judging.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prizes',
            field=models.TextField(default='1st Place: [Prize]\n2nd Place: [Prize]\n3rd Place: [Prize]'),
        ),
    ]
