# Generated by Django 4.2.7 on 2024-08-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registration_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='member1_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
