# Generated by Django 4.2.7 on 2024-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_additional_form_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='additional_form_fields',
        ),
        migrations.AddField(
            model_name='registration',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
