# Generated by Django 4.2.7 on 2024-06-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_whatsapp_group_link_alter_event_general_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_teams',
            field=models.IntegerField(default=10),
        ),
    ]
