# Generated by Django 4.2.7 on 2024-08-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration_member1_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='domain',
            field=models.CharField(blank=True, choices=[('iot', 'IoT'), ('full_stack', 'Full Stack'), ('ai_ml', 'AI/ML')], max_length=20, null=True),
        ),
    ]
