# Generated by Django 4.2.7 on 2024-06-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_max_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered_teams_count',
        ),
    ]
