# Generated by Django 4.2.7 on 2024-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_registered_teams_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered_teams_count',
            field=models.IntegerField(default=0),
        ),
    ]
