# Generated by Django 4.2.7 on 2024-08-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_registration_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='member1_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registration',
            name='members',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_name',
            field=models.CharField(max_length=255),
        ),
    ]
