# Generated by Django 4.2.7 on 2024-06-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_registered_teams_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered_teams_count',
        ),
    ]
