# Generated by Django 4.2.7 on 2024-08-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_registration_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='member1_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='members',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
    ]
