# Generated by Django 4.2.7 on 2024-06-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_registered_teams_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dates_and_deadlines',
            field=models.TextField(default='Event date \nEvent time'),
        ),
    ]
