# Generated by Django 4.2.7 on 2024-06-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_dates_and_deadlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dates_and_deadlines',
            field=models.TextField(default='Event date \\Event time'),
        ),
    ]
