# Generated by Django 4.2.7 on 2024-06-21 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_dates_and_deadlines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dates_and_deadlines',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
