# Generated by Django 4.2.7 on 2024-08-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_registration_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='member1_email',
            field=models.EmailField(blank=True, default='no-reply@example.com', max_length=254, null=True),
        ),
    ]
