# Generated by Django 4.2.7 on 2024-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_banner_image_alter_event_event_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('is_ieee_member', models.BooleanField(default=False)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.URLField(default='paste event link here'),
        ),
        migrations.AddField(
            model_name='event',
            name='student_coordinators',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.studentcoordinator'),
        ),
    ]
